version: '3.8'

services:
  gwp-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:9500"
    volumes:
      - ./backend/backups:/app/backups
      - ./backend/gwp.db:/app/gwp.db
      - ./.env:/app/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
